spring:
  datasource:
    url: jdbc:h2:mem:db?MODE=MYSQL
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: DUMMYACCESSKEY
        secret-key: dummysecretkey
      s3:
        bucket: test-bucket
        region: ap-northeast-2
        cdn-url: https://test.net/
        save-path: image-test/

logging:
  level:
    org:
      hibernate:
        SQL: debug

oauth2:
  kakao:
    url:
      profile: https://kapi.kakao.com/v2/user/me
  apple:
    url:
      profile:

jwt:
  token:
    secret-key: dWJFREY0UW1IWXNCWWRpZU4yRzJxNkRTOUltM09Dd1RCM1B4b0hBcFpCUWlqRXNMVHN6aEg2dmNtT2YvbE9PaQptcjVkdWRnSUNwakRpWkNTY2dNeld3PT0K
    expire-length:
      access: 604800000

image:
  max-upload-size: 5
  formats: jpg, jpeg, png, heic, heif # svg 일단 보류 (보안 문제, svg 만을 처리하기 위한 코드가 필요함)