spring:
  datasource:
    url: jdbc:h2:mem:db?MODE=MYSQL
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

oauth2:
  kakao:
    url:
      profile: https://kapi.kakao.com/v2/user/me
  apple:
    url:
      profile:

jwt:
  token:
    secret-key: dWJFREY0UW1IWXNCWWRpZU4yRzJxNkRTOUltM09Dd1RCM1B4b0hBcFpCUWlqRXNMVHN6aEg2dmNtT2YvbE9PaQptcjVkdWRnSUNwakRpWkNTY2dNeld3PT0K
    expire-length:
      access: 604800000
